version: v0.11.0
dsn: memory

serve:
  public:
    base_url: http://127.0.0.1:4433/
    cors:
      enabled: true
  admin:
    base_url: http://kratos:4434/

selfservice:
  default_browser_return_url: http://127.0.0.1:9090/ui/dashboard
  allowed_return_urls:
    - http://127.0.0.1:4455

  methods:
    password:
      enabled: true
    totp:
      config:
        issuer: Kratos
      enabled: true
    lookup_secret:
      enabled: true
    link:
      enabled: true
    code:
      enabled: true

  flows:
    error:
      ui_url: http://127.0.0.1:4439/error

    settings:
      ui_url: http://127.0.0.1:4439/settings
      privileged_session_max_age: 15m
      required_aal: highest_available

    recovery:
      enabled: true
      ui_url: http://127.0.0.1:4439/recovery
      use: code

    verification:
      enabled: true
      ui_url: http://127.0.0.1:4439/verification
      use: code
      after:
        default_browser_return_url: http://127.0.0.1:9090/ui/dashboard

    logout:
      after:
        default_browser_return_url: http://127.0.0.1:9090/login

    login:
      ui_url: http://127.0.0.1:9090/login
      lifespan: 10m
      after:
        password:
          hooks:
            - hook: web_hook
              config:
                url: http://coreum-processing:9090/kratos/login-user
                method: POST
                body: base64://ZnVuY3Rpb24oY3R4KSB7CiAgdXNlcjogewogICB9LAogICBpZGVudGl0eTogY3R4LmlkZW50aXR5LmlkLAogICBlbWFpbDogY3R4LmlkZW50aXR5LnRyYWl0cy5lbWFpbAp9
                response:
                  ignore: false
                auth:
                  type: api_key
                  config:
                    name: Authorization
                    value: "webhook-regi-api_key"
                    in: header
    registration:
      lifespan: 10m
      ui_url: http://127.0.0.1:9090/register
      after:
        password:
          hooks:
            - hook: session
            - hook: show_verification_ui
            - hook: web_hook
              config:
                url: http://coreum-processing:9090/kratos/create-user
                method: POST
                body: base64://ZnVuY3Rpb24oY3R4KSB7CiAgdXNlcjogewogICB9LAogICBpZGVudGl0eTogY3R4LmlkZW50aXR5LmlkLAogICBlbWFpbDogY3R4LmlkZW50aXR5LnRyYWl0cy5lbWFpbAp9
                response:
                  ignore: false
                auth:
                  type: api_key
                  config:
                    name: Authorization
                    value: "webhook-regi-api_key"
                    in: header
log:
  level: debug
  format: text
  leak_sensitive_values: true

secrets:
  cookie:
    - PLEASE-CHANGE-ME-I-AM-VERY-INSECURE
  cipher:
    - 32-LONG-SECRET-NOT-SECURE-AT-ALL

ciphers:
  algorithm: xchacha20-poly1305

hashers:
  algorithm: bcrypt
  bcrypt:
    cost: 8

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///config/identity.json

courier:
  smtp:
    connection_uri: smtps://test:test@mailslurper:1025/?skip_ssl_verify=true
