version: '3.7'
services:
  db-psql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: local-postgres0!
      POSTGRES_DB: kratos
    ports:
      - 5438:5432
    volumes:
      - ./data-db:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - db-psql
  kratos-migrate:
    depends_on:
      - db-psql
    image: oryd/kratos
    environment:
      - DSN=postgres://postgres:local-postgres0!@db-psql:5432/kratos?sslmode=disable
    volumes:
      - type: bind
        source: ./config
        target: /config
    command: -c /config/kratos.yaml migrate sql -e --yes
    restart: on-failure
    networks:
      - default
  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node
    ports:
      - "4439:4439"
    environment:
      - PORT=4439
      - SECURITY_MODE=
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4433/
    networks:
      - default
    restart: on-failure
  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=postgres://postgres:local-postgres0!@db-psql:5432/kratos?sslmode=disable
      - LOG_LEVEL=trace
    volumes:
      - type: bind
        source: ./config
        target: /config
    command: serve --dev -c /config/kratos.yaml --watch-courier
    networks:
      default:
        aliases:
          - kratos
  oauthkeeper-migrate:
    image: oryd/oathkeeper
    volumes:
      - type: bind
        source: ./config
        target: /config
    command: credentials generate --alg RS256 > /config/jwks.json
  oauthkeeper:
    image: oryd/oathkeeper
    depends_on:
      - oauthkeeper-migrate
    ports:
      - '4455:4455' # public
      - '4456:4456' # admin
    restart: unless-stopped
    environment:
      ORY_OATHKEEPER_LOG_LEVEL: debug
    volumes:
      - type: bind
        source: ./config
        target: /config
    command: serve -c /config/oathkeeper.yaml
    networks:
      default:
        aliases:
          - oauthkeeper
  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    command: serve
    networks:
      - default

  coreum-processor-migrate:
    depends_on:
      - db-psql
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - PGPASSWORD=local-postgres0!
    volumes:
      - type: bind
        source: ../cmd/scripts
        target: /migrations
    command:
      - sh
      - -c
      - |
        echo "SELECT 'CREATE DATABASE coreum_processor' WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = 'coreum_processor')\gexec" | psql -U postgres -h db-psql -p 5432 
                for migration_file in $(ls migrations/*.sql); do 
                  echo $$migration_file;
                  psql -U postgres -h db-psql -p 5432  -d coreum_processor -f $$migration_file;
                done
    restart: on-failure
    networks:
      - default

  coreum-processor:
    image: birdhousedockers/coreum_processor:latest
    depends_on:
      - coreum-processor-migrate
    ports:
      - '9090:9090'
    volumes:
      - type: bind
        source: ./config
        target: /config
    environment:
      - PORT=9090
      - TOKEN_TIME_TO_LIVE=600

      - PRIVATE_KEY=/config/keys/cryptoProcessorKey
      - PUBLIC_KEY=/config/keys/cryptoProcessorKey.key.pub
      - KRATOS_URL=http://kratos:4433

      - DATABASE_HOST=db-psql
      - DATABASE_PORT=5432
      - DATABASE_NAME=coreum_processor
      - DATABASE_USER=postgres
      - DATABASE_PASS=local-postgres0!

      - WALLET_RECEIVER_ADDRESS=testcore13f97kxrrq82982rsy2paqf9tx8e2jw5g2ufdfu
      - WALLET_RECEIVER_SEED=then donate similar only tiny voyage tribe derive spare snap wet chase divide buzz play avoid captain wonder chair announce embody primary weapon breeze
      - WALLET_SENDER_ADDRESS=testcore1w2x4hwhasqfvg8cm6kyduzgwngvp0wf46eshmc
      - WALLET_SENDER_SEED=tube pledge side laundry volume actress route pink ring galaxy vendor obscure detect patient early memory reflect glue salon valid summer scatter damp total
      #env here
    command: serve
    restart: unless-stopped
    networks:
      default:
        aliases:
          - coreum-processing
  coreum-multisign-service:
    image: birdhousedockers/coreum_multisign_service:latest
    depends_on:
      - coreum-processor
    ports:
      - '9095:9095'
    volumes:
      - type: bind
        source: ./config
        target: /config
    environment:
      - PORT=9095
      - PUBLIC_KEY=/config/keys/cryptoProcessorKey.key.pub
      - MNEMONICS=innocent beyond seed awful program shiver link flat february claw focus glimpse canvas slush forest code rough emotion juice another satisfy boil dutch unknown
      - NETWORK_TYPE=Testnet
      #env here
    command: serve
    restart: unless-stopped
    networks:
      default:
        aliases:
          - coreum-multisign-service
